FROM elixir:1.14-alpine
WORKDIR /app

RUN apk add --no-cache --update build-base git

RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV prod

COPY mix.exs /app
COPY mix.lock /app
COPY config /app
RUN mix deps.get
RUN mix deps.compile

COPY . /app
RUN mix compile
